steps:
  - id: buildkit
    name: docker:${_DOCKER_VERSION}
    args:
      - build
      - --build-arg=BUILDKIT_VERSION=${_BUILDKIT_VERSION}
      - --build-arg=DOCKER_VERSION=${_DOCKER_VERSION}
      - --cache-from=moby/buildkit:${_BUILDKIT_VERSION}
      - --cache-from=docker:${_DOCKER_VERSION}
      - --tag=gcr.io/$PROJECT_ID/buildkit:${_DOCKER_VERSION}-a08d2ea19b0a
      - --target=buildkit
      - .
    env:
      - "DOCKER_BUILDKIT=1"
    waitFor:
      - "-"

images:
  - "gcr.io/$PROJECT_ID/buildkit:${_DOCKER_VERSION}-a08d2ea19b0a"

substitutions:
  _BUILDKIT_VERSION: "master@sha256:15788cf85ad30418f2a0fc5fedf2af689c0b08d383d623eff8fec6bb277cfc69"  # moby/buildkit@a08d2ea19b0a
  _DOCKER_VERSION: "20.10"
