steps:
  - id: buildkit
    name: docker:${_DOCKER_VERSION}
    args:
      - build
      - --build-arg=BUILDKIT_VERSION=${_BUILDKIT_VERSION}
      - --build-arg=DOCKER_VERSION=${_DOCKER_VERSION}
      - --cache-from=moby/buildkit:${_BUILDKIT_VERSION}
      - --cache-from=docker:${_DOCKER_VERSION}
      - --tag=gcr.io/$PROJECT_ID/buildkit:${_DOCKER_VERSION}-159bb1e677ff
      - --target=buildkit
      - .
    env:
      - "DOCKER_BUILDKIT=1"
    waitFor:
      - "-" 

images:
  - "gcr.io/$PROJECT_ID/buildkit:${_DOCKER_VERSION}-159bb1e677ff"

substitutions:
  _BUILDKIT_VERSION: "nightly@sha256:1666985e3212b121471de9027dd1e5c54ef41155d3c0666a3b6aabf32f697055"  # moby/buildkit@159bb1e677ff
  _DOCKER_VERSION: "20.10"
